language: node_js
node_js:
  - '10.15'

cache:
directories:
  - ./node_modules

install:
  - npm install
  - npm run build
  - docker build -t="ucontas-front":latest .

script:
  - npm run test

before_deploy:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script:
    echo "---------| Generating image tags !!!  |---------";
    docker tag ucontas-front:latest $DOCKER_USERNAME/ucontas-front:$TRAVIS_JOB_ID;
    docker tag ucontas-front:latest $DOCKER_USERNAME/ucontas-front:latest;
    echo "---------| Sending to Docker HUB !!!  |---------"
    docker push $DOCKER_USERNAME/ucontas-front:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/ucontas-front:latest;
    echo "---------| Image successfully sent to Docker HUB !!!  |---------";
  on:
    brach: master
notifications:
  email: false
